### PR TITLE
Fix react getting removed in rm-requires

### PR DESCRIPTION
**Pull request by TheSavior**

### CODE REVIEW

**Comment by cpojer** [comment]
At FB we actually use "React". Can you enable both?

**Comment by TheSavior** [comment]
Woah, requires are case insensitive. TIL.

**Comment by TheSavior** [comment]
Seems like the build is failing for other reasons. The master test suite is failing too.

**Comment by cpojer** [comment]
I'll fix the CI issue. Can you add back the check for "React"?

**Pull request closed without merging**
