### PR TITLE
Add a codemod to favor object spread over `Object.assign`

### PR DESCRIPTION
**Pull request by matthieuprat**
I originally made this codemod for @doctolib but I think it's worth sharing with the community. Is it the right place to drop it?

### CODE REVIEW

**Comment by cpojer** [comment]
Nice work! Thanks for contributing.

**Comment by lencioni** [comment]
I just ran this on the Airbnb codebase and it worked really well! Thanks!

I came across one edge case that produced this diff:

```diff
-  const heightStyles = Object.assign(
-    {},
-    styles.textarea._definition,
-    large && styles.textarea_large._definition,
-    !inline && styles.block._definition,
-    // set min height for server-side rendering
-    !!minRows && { minHeight: ((2 * inputPadding(theme.unit)) + minRows * lineHeight) },
-  );
+  const heightStyles = {
+    ...styles.textarea._definition,
+    ...(large && styles.textarea_large._definition),
+    ...(!inline && styles.block._definition),
+
+    ...// set min height for server-side rendering
+    (!!minRows && { minHeight: ((2 * inputPadding(theme.unit)) + minRows * lineHeight) })
+  };
```

**Comment by lencioni** [comment]
Ah, I've also discovered some cases where comments can disappear.

```diff
-export const VERIFICATION_STEPS = Object.assign(
-  // We have "intro" and "success" pseudo-steps that we can show the user, in addition to steps
-  // corresponding to each of the verification types
-  {
-    INTRO: 'intro',
-    SUCCESS: 'success',
-  },
-  VERIFICATION_TYPES
-);
+export const VERIFICATION_STEPS = {
+  INTRO: 'intro',
+  SUCCESS: 'success',
+  ...VERIFICATION_TYPES
+};
```

**Comment by matthieuprat** [comment]
Glad you used it!

Those edge cases should be addressed by #78.

**Comment by matthieuprat** [comment]
(Comments might appear in the wrong order though. But all of them should be preserved.)

**Pull request merged**
