### PR TITLE
Add indexof-to-includes transform

### PR DESCRIPTION
**Pull request by lencioni**
This transforms code like:

```js
foo.indexOf(bar) > -1
```

to

```js
foo.includes(bar)
```

### CODE REVIEW

**Comment by cpojer** [comment]
That seems unsafe to me if an object implements an `indexOf` method that's not on an Array or String. I think I'd prefer not having this in this repo.

**Comment by lencioni** [comment]
Ok!

**Comment by lencioni** [comment]
For anyone who stumbles upon this, I just pushed a new version that preserves comments at 074a22d7e8657be86687920398af0f2450615a13

**Comment by cpojer** [comment]
Thanks for making this codemod though. I'm assuming you audited your codebase to make sure there are no data structures defining `indexOf` that don't also have an `includes` :D

**Comment by lencioni** [comment]
Yep!

**Pull request closed without merging**
