### PR TITLE
[WIP] Add transform to remove requires that are no longer needed

### PR DESCRIPTION
**Pull request by pieterv**
Not sure if this can be merged yet, the tests dont seem to be working very well locally :(

### CODE REVIEW

**Comment by cpojer** [comment]
Apparently I had notifications for my own repo off so I have never seen this before. wtf.

**Comment by cpojer** [comment]
wait, @pieterv what are we doing with this one? Also missed this, twice -.-

**Comment by pieterv** [comment]
@cpojer  oh yeah i forgot about this as well :P let me see if it still makes sense.

**Comment by pieterv** [comment]
- Covered an extra case where member expressions would stop a require being removed
- Cleaned up errors
- Added docs

\o/

**Comment by cpojer** [comment]
Awesome! Thanks for fixing this up :D

**Pull request merged**
