### PR TITLE
Fix linter warnings in no-vars.js

### PR DESCRIPTION
**Pull request by lencioni**
I noticed these warnings while running tests locally.

### CODE REVIEW

**Comment by cpojer** [comment]
thanks. Should probably make eslint throw on travis..

**Comment by lencioni** [comment]
Even if it throws, these were just warnings so it might not have thrown in this case.

**Comment by cpojer** [comment]
I think you can error on warnings, right? :)

**Comment by lencioni** [comment]
I think if you only have warnings, eslint will use an exit code of 0, which I think Travis will not fail on. You probably want to tell eslint to use errors instead of warnings for the things you care to enforce at CI.

**Pull request merged**
