### PR TITLE
Add template-literals transform

### PR DESCRIPTION
**Pull request by lencioni**
This transform replaces string concatenation with template literals.

Adapted from https://vramana.github.io/blog/2015/12/21/codemod-tutorial/

cc: @vramana

### CODE REVIEW

**Comment by lencioni** [comment]
I found an edge case that isn't correct:

```js
test = `hi ${foo} there` + `oh ${bar} hello`;
```

becomes

```js
test = `hi ${foo} there${bar}oh  hello`;
```

**Comment by lencioni** [comment]
Alright, that one is fixed. I'll keep looking for more edge cases.

**Comment by lencioni** [comment]
Here's a funky edge case:

```js
(foo + 1) + '/' + foo + '/';
```

is transformed to

```js
`${`${foo + 1}/` + foo}/`;
```

This is less than ideal, but should be safe.

After running this on a few thousand files, I feel pretty good about the safety of this transform. PTAL!

@ljharb can you come up with any wacky edge cases that should be covered here?

**Comment by ljharb** [comment]
hmm - function calls in the interpolation, nested template strings, existing template strings concatenated with non-template strings (or other values), property access (not just object literal keys), default values, computed property/method names…

**Comment by lencioni** [comment]
It seems to remove comments on template strings in arrays:

```js
[
  foo + 'bar', // comment
];
```

becomes 

```js
[
  `${foo}bar`,
];
```

This should be pretty easy to fix.

**Comment by lencioni** [comment]
```js
new RegExp(a + "\\?.*" + b);
```

becomes

```js
new RegExp(`${a}\?.*${b}`);
```

**Comment by ljharb** [comment]
the `new RegExp` case might be ok, i'm not sure if backslashes need escaping in template literals? (i'd assume they do tho)

**Comment by lencioni** [comment]
@ljharb I wasn't sure either, so I tried it out in the console and it did not seem to be okay.

**Comment by lencioni** [comment]
Alright, those issues have been resolved now.

**Comment by ljharb** [comment]
What about computed property tests? like `{ ['a' + b]: 'a' + b }` which should become `{ [`a${b}`]: `a${b}` }`, etc

**Comment by lencioni** [comment]
Thanks @ljharb! I think I have all of your cases covered in the test now. Let me know if you think of any more.

**Comment by ljharb** [comment]
I'm kind of concerned that it can't just recognize any single or double quoted string preceded or followed by a `+`, and figure out what the template string should be - i can certainly try to think of more cases, but it makes me skeptical of the reliability of the codemod. Is there something about the current approach, or the grammar involved, that makes it tricky?

**Comment by lencioni** [comment]
> I'm kind of concerned that it can't just recognize any single or double quoted string preceded or followed by a +, and figure out what the template string should be

I'm not entirely sure what you mean--can you give some concrete examples?

Are you referring to the edge case I mentioned in the areas of improvement section? (`1 + 2 + 'foo' + bar`) In this case, I decided to be conservative instead of doing something potentially dangerous. I was actually thinking about this some more this morning and am planning on taking a swing at improving this case. I think I just need to adjust how I am detecting stringish on the left in the binary expressions tree.

**Comment by ljharb** [comment]
More just raising an eyebrow at how many times an implementation change has been needed when a new test case has arrived - but it makes sense if you're being intentionally conservative.

In general, any expression that has a `+` in it, that has at least one a) hardcoded string (single, double, or backtick), or b) a `.toString()` call (which is slightly less conservative, but pretty safe i think), or c) a `String()` call (very safe, unless `String` has been locally shadowed) should be considered a "concatenated string" that needs transforming to a template literal.

**Comment by lencioni** [comment]
Ah I see. I hadn't considered `.toString()` or `String()` and I agree that they should be pretty safe, so I'll add those now. As for any expression with a `+` in it, it isn't quite that simple since `1 + 2 + 'a'` is `'3a'`, not `12a`, and `'a' + 1 + 2` is `'a12'` not `'a3'`, but yeah, that's the basic idea.

**Comment by lencioni** [comment]
@ljharb alrighty, I added some code that allows likely string casting to be concatenated in ee141cc33. Let me know if you have any more ideas!

**Comment by cpojer** [comment]
This looks like a good start to me. Given that this codemod is likely to change every file in a repo anyway, I'm fine with not adding the check for whether something has changed or not :)

@lencioni do you want to add the codemods (and their constraints) to the README in a follow-up PR?

**Pull request merged**
